#### USER-AGENT REQUEST -----> TO Create the Dataset with all the URLs
from pathlib import Path
import requests
from bs4 import BeautifulSoup
import json
from urllib.parse import urljoin
import pandas as pd
import time
import pickle
import re

print("Funtion")

#Create a data folder for the files generated by this notebook.
DATA_DIR = Path("data")
DATA_DIR.mkdir(exist_ok=True)

print(f"Data folder is ready: {DATA_DIR.resolve()}")
pickle_path = DATA_DIR / "all_pages.pkl"


# "User-Agent" REQUEST simula que la petición como si viniera desde un navegador Chrome en Windows para evitar bloqueos de HTML
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}



###########################    DEFINICIÓN DE MI FUNCIÓN PARA CADA URL    ###########################
def scrape_movie(url):
    resp = requests.get(url, headers=headers, timeout=10) ## Uso de el agente para hacer la solicitud como si viniera del navegador

    if resp.status_code != 200:
        print(f"Error HTTP {resp.status_code}: {url}")
        return None

    soup = BeautifulSoup(resp.content, "html.parser")

    # Título
    title = None
    h1 = soup.find("h1")

    if h1:
        title = h1.get_text(strip=True)
    else:
        og = soup.find("meta", property="og:title")
        if og and og.get("content"):
            title = og["content"]

####################### 0. DETERMINE CONTENT TYPE (Movie or TV Show)

    if "rottentomatoes.com/m/" in url:
        content_type = "Movie"
    elif "rottentomatoes.com/tv/" in url:
        content_type = "TV Show"
    else:
        content_type = "Unknown"

####################### 1 . CALLING GENRE(S) 

    genre = None # create the variable

    script = soup.find("script", id="mps-page-integration")

    if script:
        script_text = script.get_text()

        match = re.search(r'"cag\[genre\]":"([^"]+)"', script_text) #Looking for the text

        if match:
            genre = match.group(1)
    
    genres = [] #Save genres

    if genre:
        genres = genre.split("|") # Spplit them 

    # print("Genre:", genre)
    
################# 2. CALLING: Summary, Tomatometer, Popcornmeter

     # Variables 
    summary = None
    tomatometer = None
    popcornmeter = None

    script = soup.find("script", id="media-scorecard-json")

    if script:
        try:
            data = json.loads(script.get_text(strip=True))
            
            #Checking for texts, different forms to get the values
            summary = data.get("description")
            tomatometer = data.get("criticsScore", {}).get("scorePercent")
            popcornmeter = data.get("audienceScore", {}).get("scorePercent")

        except json.JSONDecodeError:
            pass

 ############### 3. STREAM PLATFORMS 
    platform_names = []

    for li in soup.find_all("li", attrs={"data-qa": "movies-at-home-item"}):
        a = li.find("a", href=True)

        if a and "affiliates:" in a["href"]:
            name = a.get_text(strip=True)
            platform_names.append(name)

    platform_names = list(dict.fromkeys(platform_names))

############### 4. CRITICS CONSENSUS
    critics_consensus = None

    consensus_div = soup.find("div", id="critics-consensus")

    if consensus_div:
        p = consensus_div.find("p")
        if p:
            critics_consensus = p.get_text(" ", strip=True)

    movie_row = {
        "title": title,
        "content_type": content_type,
        "genre": genre,
        "url": url,
        "tomatometer": tomatometer,
        "popcornmeter": popcornmeter,
        "summary": summary,
        "critics_consensus": critics_consensus,
        "platforms": ", ".join(platform_names)
    }

    return movie_row ## Me retorna el valor de cada columna nueva


################################# Fin de la función ######################


# #Cargo mi archivo pkl ### MAS ADELANTE SE ACTUALIZA CON TODAS LAS SERIES Y PEL[ICULAS]
# with pickle_path.open("rb") as f:
#     all_series_urls = pickle.load(f)


pickle_path1 = DATA_DIR / "all_pages.pkl"


with open(pickle_path1, "rb") as f:
    list1 = pickle.load(f)


combined_list = list1
combined_list = list(dict.fromkeys(combined_list))  # Remover duplicados
# combined_list

#####  For para crear la matriz
rows = []

for i, url in enumerate(combined_list, start=1):
    # print(f"Scrapeando {i}/{len(movie_urls)}: {url}")

    movie_row = scrape_movie(url)

    if movie_row is not None:
        rows.append(movie_row)

    time.sleep(1)

#### Creación del DataFrame 
df = pd.DataFrame(rows)


#### Guardar EL dataframe
df.to_csv("rottentomatoes_dataset.csv", index=False, encoding="utf-8")
