from pathlib import Path
import numpy as np  
import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import json
import pickle
import time

print("This is the start of the scraping")


#Create a data folder for the files generated by this notebook.
DATA_DIR = Path("data")
DATA_DIR.mkdir(exist_ok=True)

print(f"Data folder is ready: {DATA_DIR.resolve()}")
pickle_path = DATA_DIR / "all_pages.pkl"


search_bases = [
    "https://www.rottentomatoes.com/browse/movies_at_home/affiliates:fandango-at-home",
    "https://www.rottentomatoes.com/browse/movies_at_home/affiliates:netflix",
    "https://www.rottentomatoes.com/browse/movies_at_home/affiliates:apple-tv-plus",
    "https://www.rottentomatoes.com/browse/movies_at_home/affiliates:prime-video",
    "https://www.rottentomatoes.com/browse/movies_at_home/sort:popular",
    "https://www.rottentomatoes.com/browse/movies_at_home/critics:certified_fresh",
    "https://www.rottentomatoes.com/browse/movies_at_home/",
    "https://www.rottentomatoes.com/browse/movies_in_theaters/sort:newest",
    "https://www.rottentomatoes.com/browse/movies_at_home/sort:popular",
    "https://www.rottentomatoes.com/browse/tv_series_browse/sort:popular",
]

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}

all_series_urls = []
count_error = 0

for base_url in search_bases:
    for page in range(1, 12):  # páginas 1 a 11
        url = f"{base_url}?page={page}"
        # print(f"Scrapeando página {page}: {url}")

        resp = requests.get(url, headers=headers, timeout=10)

        
        if resp.status_code != 200:
            count_error += 1
            ##### Error if the page has not been created
            print(f"Error en página {page} de {base_url}: HTTP {resp.status_code}") 
            
            #print(count_error)
            continue # If the error happens, continue with next page

        soup = BeautifulSoup(resp.content, "html.parser")

        for a in soup.find_all("a", href=True):
            full_url = urljoin(url, a["href"])

            if "rottentomatoes.com/tv/" in full_url:
                all_series_urls.append(full_url)
            elif"rottentomatoes.com/m/" in full_url:
                all_series_urls.append(full_url)

        time.sleep(1)  # pausa pequeña para no saturar la página

# Quitar duplicados
all_series_urls = list(dict.fromkeys(all_series_urls))


print(f"\nTotal de series encontradas: {len(all_series_urls)}")
for u in all_series_urls:
    print(u)

with open(DATA_DIR / "all_pages.pkl", "wb") as f:
    pickle.dump(all_series_urls, f)


